### ISSUE TITLE
Have a problem with migrations: AttributeError: 'ForeignObjectRel' object has no attribute 'through'

### ISSUE THREAD

**Issue by emacsway** [onysos/django-composite-foreignkey#15]
```
(.env) ivan@ivan-X555LF:/extra1/biz-tek/cms-medical$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, menu, posts, sessions, users, versioning
Running migrations:
  Applying posts.0018_auto_20180504_0306...Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 491, in alter_field
    old_field.remote_field.through and new_field.remote_field.through and
AttributeError: 'ForeignObjectRel' object has no attribute 'through'
```

**Comment by emacsway** [comment]
When I try to fix the issue:
```
from django.db.models.fields.reverse_related import ForeignObjectRel
ForeignObjectRel.through = None
```
then I have got another issue:

```
(.env) ivan@ivan-X555LF:/extra1/biz-tek/cms-medical$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, menu, posts, sessions, users, versioning
Running migrations:
  Applying posts.0018_auto_20180504_0306...Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/extra1/biz-tek/.env/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 505, in alter_field
    "through= on M2M fields)" % (old_field, new_field)
ValueError: Cannot alter field posts.PostElementVersion.post into posts.PostElementVersion.post - they are not compatible types (you cannot alter to or from M2M fields, or add or remove through= on M2M fields)
```

**Comment by emacsway** [comment]
A similar problem: https://groups.google.com/d/topic/django-developers/_FmJRK3sJGs/discussion

**Comment by emacsway** [comment]
A Monkey patch to workaround:
```

+from compositefk.fields import ForeignObject, CompositeForwardManyToOneDescriptor, CompositeForeignKey
+
+
+def contribute_to_class(self, cls, name, **kwargs):
+    kwargs['private_only'] = True
+    super(ForeignObject, self).contribute_to_class(cls, name, **kwargs)
+    setattr(cls, self.name, CompositeForwardManyToOneDescriptor(self))
+
+CompositeForeignKey.contribute_to_class = contribute_to_class
```

**Comment by ghost** [comment]
has this problem solved ？
